#
###################################
# Site wide configuration
####################################
#
title: Wanderlust
email: xil154@pitt.edu
description: A simple blog
url: https://vagarii.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/New_York
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: XinLai
  avatar: 
  job: "A blog"
  bio: "A simple and awesome blog powered by jekyll."
  email: xil154@pitt.edu
  disqus-shortname:
  twitter: barbaralai
  facebook: Xin Lai
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: vagarii
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: XIL154@pitt.edu
  xing: #username
  instagram: xinlai98
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
